# Generated by Django 4.0.4 on 2022-05-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(default=0)),
                ('telefono', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=50)),
                ('fecha_nac', models.DateTimeField(verbose_name='date published')),
                ('fecha_public', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
